name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate snake.svg
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: LuuAiGiao
          outputs: dist/snake.svg
          configuration: |
            theme: dark
            background: black

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
